//------------------------------------------------------------------------------
// <auto-generated>
//     This core generates by tool.
//     Run version: 4.0.30319.296
//
//     Change this file may cause incorrect behavior,
//     and these change will be lost if regenerate core.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceManager.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly typed resource class, for finding localized character strings, etc.
    /// </summary>
    // This type is auto-generated by StronglyTypedResourceBuilder
    // auto-generated via tools like ResGen or Visual Studio.
    // To add or move member, edit .ResX file and re-run ResGen
    // (Take /str as command option), or re-generate VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Return to the using cached ResourceManager example.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UHFDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Use this strongly typed resource, for all resource find
        ///   Rewrite CurrentUICulture attribute of current thread.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
