//------------------------------------------------------------------------------
// <auto-generated>
//     This core generates by tool.
//     Run version: 4.0.30319.296
//
//     Change this file may cause incorrect behavior,
//     and these change will be lost if regenerate core.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceManager.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
